services:
  frontend:
    image: ghcr.io/ensslinadrian/aden-frontend-library:latest
    build:
      context: ./aden-frontend-library
      args:
        API_URL: ${FRONTEND_API_URL}
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${FRONTEND_VIRTUAL_HOST}
      - VIRTUAL_PORT=${FRONTEND_VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${FRONTEND_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${DEFAULT_FROM_EMAIL}
    depends_on:
      - backend
    networks:
      - backend-network
      - proxy

  backend:
    image: ghcr.io/ensslinadrian/aden-backend-library:latest
    build:
      context: ./aden-backend-library
    restart: unless-stopped
    env_file: .env
    environment:
      - VIRTUAL_HOST=${BACKEND_VIRTUAL_HOST}
      - VIRTUAL_PORT=${BACKEND_VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${BACKEND_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${DEFAULT_FROM_EMAIL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network
      - proxy
    volumes:
      - media:/app/media
      - static:/app/static

  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend-network
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery:
      image: ghcr.io/ensslinadrian/aden-backend-library:latest
      restart: unless-stopped
      entrypoint: ./celery.entrypoint.sh
      env_file: .env
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
      networks:
        - backend-network

  celery_beat:
    image: ghcr.io/ensslinadrian/aden-backend-library:latest
    restart: unless-stopped
    entrypoint: ./celery_beat.entrypoint.sh
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network

volumes:
  postgres_data:
  redis_data:
  static:
  media:

networks:
  backend-network:
  proxy:
    external: true